INSERT INTO DIMDATE_DLT
SELECT TO_CHAR(DATETIME,'YYYYMMDDHH24MI')
FROM VIDEOSTART_DLT
GROUP BY TO_CHAR(DATETIME,'YYYYMMDDHH24MI')
ORDER BY TO_CHAR(DATETIME,'YYYYMMDDHH24MI');

INSERT INTO DIMPLATFORM_DLT
SELECT PLATFORM
FROM VIDEOSTART_DLT
GROUP BY PLATFORM
ORDER BY PLATFORM;

INSERT INTO DIMSITE_DLT
SELECT SITE
FROM VIDEOSTART_DLT
GROUP BY SITE
ORDER BY SITE;

INSERT INTO DIMVIDEO_DLT
SELECT VIDEO
FROM VIDEOSTART_DLT
GROUP BY VIDEO
ORDER BY VIDEO;

commit;